<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nav-flyout-buffer-left</name>
   <tag></tag>
   <elementGuidId>4aa4174a-3603-40bc-b97f-587a2115b7bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-icp']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-flyout-icp > div.nav-flyout-buffer-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f4a58a6-5785-498d-9b81-d241daf462f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-flyout-buffer-left</value>
      <webElementGuid>bd60c9e1-e055-48f9-84f3-9abece736c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-icp&quot;)/div[@class=&quot;nav-flyout-buffer-left&quot;]</value>
      <webElementGuid>b78ce31c-93f0-4ee1-9f84-0d400d478997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-icp']/div[3]</value>
      <webElementGuid>c23cb55f-7913-4b7e-a267-ca89853bd6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[3]</value>
      <webElementGuid>5c9244a3-2287-428c-87ad-b9baaac010aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
