<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_espaol - ES</name>
   <tag></tag>
   <elementGuidId>922d7033-bbf0-4444-bd8f-f35fce3259c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-icp']/div[2]/a[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b93cd3ad-c77b-4789-9db1-034e7ab69d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-text</value>
      <webElementGuid>9392abe7-b858-420e-b3e9-c868042f092c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>español - ES</value>
      <webElementGuid>293c505f-e22a-42b5-aed6-bc269336f5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-icp&quot;)/div[@class=&quot;nav-template nav-flyout-content nav-tpl-itemList&quot;]/a[@class=&quot;nav-link                                    nav-item&quot;]/span[@class=&quot;nav-text&quot;]</value>
      <webElementGuid>4549fcd0-b331-46e8-8df7-30fce6fca3f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-icp']/div[2]/a[2]/span</value>
      <webElementGuid>18977180-3092-40cc-a574-1a48b7320e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/a[2]/span</value>
      <webElementGuid>6ed0bdc6-d4db-4354-95fb-3797b0f83aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'español - ES' or . = 'español - ES')]</value>
      <webElementGuid>b815c421-bda3-4f79-80da-6e680242e570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
