<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EUR</name>
   <tag></tag>
   <elementGuidId>563fa955-cf00-44cb-b7c2-67bd310cf270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='octopus-dlp-asin-stream']/ul/li/span/div/div[2]/div[4]/span[2]/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-price-symbol</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b5bb289-4c5a-4089-8515-d75a29d4a1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-price-symbol</value>
      <webElementGuid>009d9f14-f2d8-481e-9b94-b84f8a6a5e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EUR</value>
      <webElementGuid>54ef70cf-2e34-478a-bd5d-b40b21c1feff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;octopus-dlp-asin-stream&quot;)/ul[@class=&quot;a-unordered-list a-nostyle a-horizontal a-spacing-none&quot;]/li[@class=&quot;a-list-normal a-spacing-none no-margin-right overflow-hidden octopus-response-li-width&quot;]/span[@class=&quot;a-list-item&quot;]/div[@class=&quot;a-section octopus-dlp-asin-section&quot;]/div[@class=&quot;a-section octopus-dlp-asin-info-section&quot;]/div[@class=&quot;a-row octopus-dlp-price&quot;]/span[@class=&quot;a-price octopus-widget-price&quot;]/span[2]/span[@class=&quot;a-price-symbol&quot;]</value>
      <webElementGuid>a1570645-208e-49f4-bb6e-df6cd70a0e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='octopus-dlp-asin-stream']/ul/li/span/div/div[2]/div[4]/span[2]/span[2]/span</value>
      <webElementGuid>e4346feb-9fd6-4023-8afd-25d22639b44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span[2]/span</value>
      <webElementGuid>8be3edb9-0cc6-4776-af28-2a50d0e5ff53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'EUR' or . = 'EUR')]</value>
      <webElementGuid>e9118ec1-b484-40a9-9865-8d0776274518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
