<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>32a358cd-8600-4bf5-90a0-56e033c4149d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Womens Running Shoes Slip-on Walking Tennis Sneakers Lightweight Breathable Casual Soft Sole Mesh Workout Sports Shoes&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='itemImage_I112FNH5SKU1TT']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87a1ab5a-1490-4805-8747-3c8f4540f411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Womens Running Shoes Slip-on Walking Tennis Sneakers Lightweight Breathable Casual Soft Sole Mesh Workout Sports Shoes</value>
      <webElementGuid>1e32c5d4-08c3-4930-b1c6-35f99a6949f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/41PRzWti+wL._SS135_.jpg</value>
      <webElementGuid>c6b52ba2-6eb0-4233-9ffb-1c2c93648443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>135</value>
      <webElementGuid>e0597029-a913-4ce4-bed2-424f66366ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>135</value>
      <webElementGuid>b29525f6-09c2-4acf-b17d-265c820fc818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemImage_I112FNH5SKU1TT&quot;)/a[@class=&quot;a-link-normal&quot;]/img[1]</value>
      <webElementGuid>e648ab84-bb88-43f3-8ae9-ce12f191f789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itemImage_I112FNH5SKU1TT']/a/img</value>
      <webElementGuid>44312c21-9188-4161-92d3-fbe0f3bbacee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Womens Running Shoes Slip-on Walking Tennis Sneakers Lightweight Breathable Casual Soft Sole Mesh Workout Sports Shoes']</value>
      <webElementGuid>3a5d3dce-dee7-4763-9c6b-86ee91d3149d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>8d7b3384-926e-4345-a663-2121b86a4741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Womens Running Shoes Slip-on Walking Tennis Sneakers Lightweight Breathable Casual Soft Sole Mesh Workout Sports Shoes' and @src = 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/41PRzWti+wL._SS135_.jpg']</value>
      <webElementGuid>ff62ec2a-c434-4bc4-b3c9-7758dd259032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
