<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__cropped-image-link_style_fluidLandscap_8e93c3</name>
   <tag></tag>
   <elementGuidId>abcceda5-826f-4a4c-9af4-3fdc2570b35c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceK9SXl6Vw_6SxpdTUDUxNVg']/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CardInstanceK9SXl6Vw_6SxpdTUDUxNVg > a.a-link-normal._cropped-image-link_style_centerImage__1rzYI.aok-block.image-window > div.a-section.a-spacing-none._cropped-image-link_style_fluidImageContainer__2jd50 > img._cropped-image-link_style_fluidLandscapeImage__3eTVC._cropped-image-link_style_fluidImage__iJ3aE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b251e39a-fdfa-49a7-849a-6569fdef834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Año Nuevo lunar</value>
      <webElementGuid>91276ee7-8e40-4739-85ff-4423917aa177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71b86qdeRXL._SX3000_.jpg</value>
      <webElementGuid>d2819f44-6293-4166-8d45-f5509a97cc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_cropped-image-link_style_fluidLandscapeImage__3eTVC 
 _cropped-image-link_style_fluidImage__iJ3aE</value>
      <webElementGuid>b42f5468-57bc-4689-a8be-bfeee5b9b943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71b86qdeRXL._SX3000_.jpg</value>
      <webElementGuid>b5f7d54e-8674-4056-9e3f-4795e840f8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceK9SXl6Vw_6SxpdTUDUxNVg&quot;)/a[@class=&quot;a-link-normal _cropped-image-link_style_centerImage__1rzYI aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none _cropped-image-link_style_fluidImageContainer__2jd50&quot;]/img[@class=&quot;_cropped-image-link_style_fluidLandscapeImage__3eTVC 
 _cropped-image-link_style_fluidImage__iJ3aE&quot;]</value>
      <webElementGuid>a6644970-9221-40c5-afa2-5e6e596f0f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceK9SXl6Vw_6SxpdTUDUxNVg']/a/div/img</value>
      <webElementGuid>5ba7c414-0e37-411c-adab-1e7e429b4f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Año Nuevo lunar']</value>
      <webElementGuid>386bae39-184e-43b2-b23e-d5a5e8d0e26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/a/div/img</value>
      <webElementGuid>fbb1d6bb-85d2-42fd-ba45-80c7ba0ff13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Año Nuevo lunar' and @src = 'https://m.media-amazon.com/images/I/71b86qdeRXL._SX3000_.jpg']</value>
      <webElementGuid>e3bb27a5-3314-428d-9c4b-7419d2dc3f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
