<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HP 15.6 HD Student Laptop, Intel Penti_711c8c</name>
   <tag></tag>
   <elementGuidId>9cfac043-fbd1-4d84-bc1e-dc64353e02a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96b9731b-38ad-493d-a4d5-063500cd4695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>9ae27944-7e2a-440d-850a-df164f29e288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-large product-title-word-break</value>
      <webElementGuid>c120597a-af07-4dc1-8ddf-177127c4ba07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        HP 15.6&quot; HD Student Laptop, Intel Pentium Silver N5030, 16GB RAM, 1TB PCIe SSD, Intel UHD Graphics, HD Webcam, Numpad, Wi-Fi 5, Bluetooth, Windows 11, Blue, 32GB Hotface USB Card       </value>
      <webElementGuid>755333a9-9f84-44dd-800b-bef329204cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title&quot;)/span[@id=&quot;productTitle&quot;]</value>
      <webElementGuid>0b208d95-1c2c-4e68-a44f-5e25829a0228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>bf879908-2c9e-4924-8408-d04c573852a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='title']/span</value>
      <webElementGuid>6e1342cf-9387-4513-828c-85323136a2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>71d55756-a89a-4257-9308-15c0863ba957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productTitle' and (text() = '        HP 15.6&quot; HD Student Laptop, Intel Pentium Silver N5030, 16GB RAM, 1TB PCIe SSD, Intel UHD Graphics, HD Webcam, Numpad, Wi-Fi 5, Bluetooth, Windows 11, Blue, 32GB Hotface USB Card       ' or . = '        HP 15.6&quot; HD Student Laptop, Intel Pentium Silver N5030, 16GB RAM, 1TB PCIe SSD, Intel UHD Graphics, HD Webcam, Numpad, Wi-Fi 5, Bluetooth, Windows 11, Blue, 32GB Hotface USB Card       ')]</value>
      <webElementGuid>eff03b26-f9fa-4e71-b5c9-f51706505f10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
