<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_a-icon a-icon-radio</name>
   <tag></tag>
   <elementGuidId>9a3d883d-b839-4244-9806-104c1ac137a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='icp-language-settings']/div[2]/div/label/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-icon-radio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9580e98e-247a-40d8-be43-0152d7ed2266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-radio</value>
      <webElementGuid>7b22b6f6-ac79-4cb1-b6e4-c0fc0d7817c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-language-settings&quot;)/div[@class=&quot;a-row a-spacing-mini&quot;]/div[@class=&quot;a-radio a-radio-fancy&quot;]/label[1]/i[@class=&quot;a-icon a-icon-radio&quot;]</value>
      <webElementGuid>095b0ac5-5a67-4702-946a-0a15bb4a75d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='icp-language-settings']/div[2]/div/label/i</value>
      <webElementGuid>9d6f345b-5d7b-4a1f-a0f4-b92a2ad31ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
      <webElementGuid>4892ed29-f5f3-477c-ad9d-64973b92af70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
