<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TL_TS_SearchField_Validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1a4e9dcb-cab3-472e-b841-7d8bc04f6b9b</testSuiteGuid>
   <testCaseLink>
      <guid>3df2b603-1f76-4287-b9aa-ee85a99a0215</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestListener/TC_013_Amazon_ ValidateSearchFieldItem _TListener</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b1f507dc-021d-496a-ba46-61daeb540ec9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test_Data/SearchField_TD_002</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b1f507dc-021d-496a-ba46-61daeb540ec9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>ee0fb4dd-3145-4d9c-85d0-6fea5892c246</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b1f507dc-021d-496a-ba46-61daeb540ec9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>9e2ba6ea-9af0-4149-9614-b7dd2f56fe83</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
