<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_DealImage-module__imageObjectFit_1G4pEk_b26014</name>
   <tag></tag>
   <elementGuidId>271ff7be-9bb1-469e-8160-f8fd24a2eb5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid-main-container']/div[3]/div/div[2]/div/div/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>83924150-26fc-45fb-b9ce-c5e9392aec35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Beats Earbuds</value>
      <webElementGuid>9129feae-66fe-4575-bd1a-77eab0fcbe2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/3170AhtjmBL._AC_UF226,226_FMjpg_.jpg</value>
      <webElementGuid>8e58afd4-bcc1-41e9-a15c-5c196bb6879f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DealImage-module__imageObjectFit_1G4pEkUEzo9WEnA3Wl0XFv</value>
      <webElementGuid>b2e08a72-bf59-4ef2-9bce-ebaf54ad5f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/3170AhtjmBL._AC_UF452,452_FMjpg_.jpg</value>
      <webElementGuid>0133031c-fd62-4927-8598-007600e86a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-main-container&quot;)/div[@class=&quot;a-row Grid-module__gridSection_1SEJTeTsU88s6aVeuuekAp&quot;]/div[@class=&quot;Grid-module__gridDisplayGrid_2X7cDTY7pjoTwwvSRQbt9Y&quot;]/div[@class=&quot;DealGridItem-module__dealItemDisplayGrid_e7RQVFWSOrwXBX4i24Tqg DealGridItem-module__withBorders_2jNNLI6U1oDls7Ten3Dttl DealGridItem-module__withoutActionButton_2OI8DAanWNRCagYDL2iIqN&quot;]/div[@class=&quot;DealGridItem-module__dealItemContent_1vFddcq1F8pUxM8dd9FW32&quot;]/div[@class=&quot;DealCard-module__card_1u9yKYV4EIA-fL4ibeMVIU DealCard-module__cardWithoutActionButton_1K_FldevdoXxE8uy5pzBmr&quot;]/a[@class=&quot;a-link-normal DealCard-module__linkOutlineOffset_2fc037WfeGSjbFp1CAhOUn&quot;]/div[@class=&quot;DealCard-module__cardImageVertical_1m9E6mjbE6UbrGJwvn6GKM DealCard-module__imageWithPadding_Qk9F2b8bUeXPk8FUBnSVG&quot;]/div[@class=&quot;a-image-container a-dynamic-image-container aok-align-center-horizontally DealImage-module__image_1aM-S1pMSsajamWgCRXa6y DealImage-module__imageAspectRatioFix_DJdrM5BSpMhSiPB6czCA4&quot;]/img[@class=&quot;DealImage-module__imageObjectFit_1G4pEkUEzo9WEnA3Wl0XFv&quot;]</value>
      <webElementGuid>b2f3a05a-09db-4a78-ac1a-d87435391abb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-main-container']/div[3]/div/div[2]/div/div/a/div/div/img</value>
      <webElementGuid>1b71060b-3dd2-4dcb-94b6-85c31e8bdfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Beats Earbuds']</value>
      <webElementGuid>173251e0-dfc1-4d2c-b7c6-c5bc4afaea30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/div/img</value>
      <webElementGuid>aeaffbb4-18dc-450b-b9bb-ad28b1e0f25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Beats Earbuds' and @src = 'https://m.media-amazon.com/images/I/3170AhtjmBL._AC_UF226,226_FMjpg_.jpg']</value>
      <webElementGuid>011362d6-1c1b-42e3-9312-471846c81dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
