<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TL_TS_AmazonLogin_searchfield_validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f20d42ed-ae2b-4983-b0d8-87063fa3c406</testSuiteGuid>
   <testCaseLink>
      <guid>1a729e1c-ff3a-46b8-9895-52b88d7889be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmazonLogin_Page/TC_001_Amazon_login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2e28cc1-16a4-4b36-a30f-7c0d5b9e93e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25af8b48-58c1-4860-8362-dce18c61d53b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b9259a1-c659-45f5-8c87-b97a814799af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmazonLogin_Page/TC_002_SearchField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28279c7f-79ef-46f4-b7cc-4f21ca7f920c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45178b4a-c76e-44fd-a179-f852a45da17c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
