<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_ValidateSearchField__002</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cca5d9ab-531c-4243-a9c0-94f49090a794</testSuiteGuid>
   <testCaseLink>
      <guid>81588cee-0750-4d04-86a7-f610292dd59d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmazonLogin_Page/TC_002_SearchField</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>127f1679-1af3-4b2e-aaf9-78472dc62ff2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test_Data/SearchField_TD_002</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>127f1679-1af3-4b2e-aaf9-78472dc62ff2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>28279c7f-79ef-46f4-b7cc-4f21ca7f920c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>127f1679-1af3-4b2e-aaf9-78472dc62ff2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>45178b4a-c76e-44fd-a179-f852a45da17c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
