<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_In Stock</name>
   <tag></tag>
   <elementGuidId>f1b1deeb-2a5d-4f0a-ad28-e8bf6be8afaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-size-medium.a-color-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='availability']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66a6b8ae-ca61-4eaa-bd0a-9d22262e19dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-medium a-color-success</value>
      <webElementGuid>49c2b6f8-c3be-41c3-9211-75b826fe3e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> In Stock </value>
      <webElementGuid>e18d290a-a782-484d-bbb9-c8e84fb04b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availability&quot;)/span[@class=&quot;a-size-medium a-color-success&quot;]</value>
      <webElementGuid>a4993236-7eda-4ff9-b85b-e800fe2448ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='availability']/span</value>
      <webElementGuid>db649674-6cc0-4659-a11a-4a276a0ba0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[6]/div/div/span</value>
      <webElementGuid>eb37c52e-ebae-49d5-bce6-27ab4fe94da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' In Stock ' or . = ' In Stock ')]</value>
      <webElementGuid>113d3625-1e4b-4f30-9279-b839382e8cd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
