<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go to Cart</name>
   <tag></tag>
   <elementGuidId>8ec581a5-7cb5-4ac6-a53e-d0e5a40aa661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sw-gtc > span.a-button-inner > a.a-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sw-gtc']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47b3b092-2ca0-4abc-ae03-1ef703f54102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart?ref_=sw_gtc</value>
      <webElementGuid>2f5a1c3a-b90d-48e2-9e47-4cb0da68edf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>sw-gtc_CONTENT</value>
      <webElementGuid>031bd1a7-c92f-4ed5-b3f8-a09f95923cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>sw-gtc</value>
      <webElementGuid>b0f7430a-627b-4e0a-a193-8122a3995c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4743d677-8a36-427f-8122-d531c9c16e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>22f61c35-05b4-48f5-877f-80cafda4b2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>cic3c8-sfnada-kawf0b-4unjnu</value>
      <webElementGuid>c782daab-9684-4586-842a-791d0a51a384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Go to Cart
</value>
      <webElementGuid>6a7229d7-6dd7-4aa0-8694-137a87044c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-gtc&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>0740f880-83cc-4277-85bf-d577d6a77fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sw-gtc']/span/a</value>
      <webElementGuid>737b6eaf-e0a5-41e4-8eec-d34e40ac1c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Go to Cart')])[2]</value>
      <webElementGuid>984ece3c-25c6-4993-866f-864af4646e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart?ref_=sw_gtc')]</value>
      <webElementGuid>a25bdd4b-f022-4ae1-ac49-b68b00ec5860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/span/span/a</value>
      <webElementGuid>929f8f58-f04f-4998-89d8-4caf98cc0bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart?ref_=sw_gtc' and (text() = '
    Go to Cart
' or . = '
    Go to Cart
')]</value>
      <webElementGuid>1c569433-dc02-4f09-964c-f84bb6edbd1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
