<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_link_delete</name>
   <tag></tag>
   <elementGuidId>5c1733c9-b336-47c1-83d0-8d1a17930727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.delete.6cd429d3-c06a-432b-b6e4-56d6193ac57b&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sc-active-eb492738-65b4-4450-98dc-b44e0e503875&quot;]/div[4]/div/div[2]/div[1]/span[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5627f5a8-b867-4542-8400-f43486143c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.delete.6cd429d3-c06a-432b-b6e4-56d6193ac57b</value>
      <webElementGuid>8ce15193-30b1-4942-be51-e0b61d6bc8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>5a338c28-2736-4ac7-9446-0a5681fa3f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>99f92c81-e642-4845-b8e2-d33d7f5bc9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Delete Turtle Beach Ear Force Recon 50 Gaming Headset for PlayStation 4, Xbox One, &amp;amp; PC/Mac</value>
      <webElementGuid>49196dd3-61f8-4766-864f-c456cdf23fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dc4f7e1d-ce99-4b7b-aa0c-3e0d8eb4c4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>252fbd71-ee98-4d1e-a2d6-3cee96ba5afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-6cd429d3-c06a-432b-b6e4-56d6193ac57b&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;sc-item-content-group&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-delete&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>b7940327-bf68-4d01-a8a6-15db3825c6d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.delete.6cd429d3-c06a-432b-b6e4-56d6193ac57b']</value>
      <webElementGuid>09ce3c06-8327-4d09-b26d-766957045810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-6cd429d3-c06a-432b-b6e4-56d6193ac57b']/div[4]/div/div[2]/div/span[2]/span/input</value>
      <webElementGuid>13feedda-bb08-4eb8-8ebb-8e8304b281c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>aa33bd0c-ea4a-4069-9310-e613b32c0d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.delete.6cd429d3-c06a-432b-b6e4-56d6193ac57b' and @type = 'submit']</value>
      <webElementGuid>aac1534c-d898-4609-b601-09e81cb0b2f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
