<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iicon-checkbox</name>
   <tag></tag>
   <elementGuidId>ac408612-7244-4e85-b606-4004a24bf2ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3 > div.a-checkbox.a-checkbox-fancy > label > i.a-icon.a-icon-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3']/div/label/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bdf25fb8-4579-47b2-95ea-781a77d84ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-checkbox</value>
      <webElementGuid>3e59e208-cf65-40ac-86ce-cfea3ec674f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/div[@class=&quot;a-checkbox a-checkbox-fancy&quot;]/label[1]/i[@class=&quot;a-icon a-icon-checkbox&quot;]</value>
      <webElementGuid>3e6b6ba1-7ca6-48e9-a4b4-83cd65a04e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div/label/i</value>
      <webElementGuid>65ead008-f00a-47fd-a507-d4d4339e9656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/label/i</value>
      <webElementGuid>9d354380-8702-4912-8fe7-0d6d0e2970fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
