<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Your List</name>
   <tag></tag>
   <elementGuidId>0ebb6c42-dda7-459c-81a2-d23719b875fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#huc-view-your-list-button > span.a-button-inner > a.a-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='huc-view-your-list-button']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>155cf0fd-4203-4d09-828a-441346a83198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/hz/wishlist/ls/RP1AMJ0SM7E5?ref_=wl_dp_view_your_list</value>
      <webElementGuid>977cf1cc-cc90-45cf-a511-e4dcc713a1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>f398a5fe-409c-423a-bace-8381fecb2261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Your List</value>
      <webElementGuid>a38d68e5-a8cd-449a-bca3-a3268ee3ee9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;huc-view-your-list-button&quot;)/span[@class=&quot;a-button-inner&quot;]/a[@class=&quot;a-button-text&quot;]</value>
      <webElementGuid>cef7a9a2-52ee-4634-a9b7-063dac479f92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='huc-view-your-list-button']/span/a</value>
      <webElementGuid>30780d45-e5f2-4263-b814-1900e0e05e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Your List')]</value>
      <webElementGuid>63e67d08-f362-4513-8047-0bb58a1dc241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We', &quot;'&quot;, 've moved it to the top of the list.')])[1]/following::a[2]</value>
      <webElementGuid>fc0ff188-c935-46e9-b359-958cd8a75de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping List'])[1]/following::a[2]</value>
      <webElementGuid>96085e32-fe56-47ea-95b3-70b5c7b8fc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Your List']/parent::*</value>
      <webElementGuid>e0d1bcca-b090-407e-b6fa-010e125969eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/hz/wishlist/ls/RP1AMJ0SM7E5?ref_=wl_dp_view_your_list')]</value>
      <webElementGuid>964239b1-5a9b-46ae-8028-9a835ea6a70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/span/a</value>
      <webElementGuid>c4f012b7-f4f9-4cc7-9c41-f245fdd13570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com/hz/wishlist/ls/RP1AMJ0SM7E5?ref_=wl_dp_view_your_list' and (text() = 'View Your List' or . = 'View Your List')]</value>
      <webElementGuid>8b4427e9-a58b-4961-a548-df54e66f4182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
