<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__fluid-fat-image-link-v2_style_fluidLan_075a06</name>
   <tag></tag>
   <elementGuidId>5827d95b-c5c4-40d9-8d8d-144e553f0887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstance-MiDpf4KXbcGb9ItQLoT6Q']/a/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img._fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK._fluid-fat-image-link-v2_style_fluidImage__gTBjA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c193bc23-1b15-4713-99ba-6c9e2262b747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>New year, new supplies</value>
      <webElementGuid>90b51954-d8c9-4bf8-8bf3-55d20b1c93af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/US-hq/2023/img/Consumer_Electronics/XCM_CUTTLE_1555947_2997386_379x304_1X_en_US._SY304_CB594429819_.jpg</value>
      <webElementGuid>a199f46c-4821-4310-8e1b-795e494cf28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK _fluid-fat-image-link-v2_style_fluidImage__gTBjA</value>
      <webElementGuid>2265a6f2-24a9-47e0-81ca-0fa1ed0afb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/US-hq/2023/img/Consumer_Electronics/XCM_CUTTLE_1555947_2997386_758x608_2X_en_US._SY608_CB594429819_.jpg</value>
      <webElementGuid>9172b7c7-308e-4a2c-b47c-a289cded9c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstance-MiDpf4KXbcGb9ItQLoT6Q&quot;)/a[@class=&quot;a-link-normal _fluid-fat-image-link-v2_style_mergedLinks__10JqZ&quot;]/div[@class=&quot;_fluid-fat-image-link-v2_style_fluidFatImageLinkBody__1LsOX&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-fat-image-link-v2_style_fluidImageContainer__2SOMr&quot;]/img[@class=&quot;_fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK _fluid-fat-image-link-v2_style_fluidImage__gTBjA&quot;]</value>
      <webElementGuid>06e23753-ed35-4ec7-a360-3b7fd38479c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstance-MiDpf4KXbcGb9ItQLoT6Q']/a/div/div/img</value>
      <webElementGuid>2da6410b-b2ff-4660-a723-907776b7c53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='New year, new supplies']</value>
      <webElementGuid>00d696f7-1bfe-4cee-beb4-3df448f80f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>39c35e27-435f-4e7d-874d-22d9f43765b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'New year, new supplies' and @src = 'https://images-na.ssl-images-amazon.com/images/G/01/US-hq/2023/img/Consumer_Electronics/XCM_CUTTLE_1555947_2997386_379x304_1X_en_US._SY304_CB594429819_.jpg']</value>
      <webElementGuid>4c138ba9-24b4-49bc-9a18-a96a419b074d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
