<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a-button-input</name>
   <tag></tag>
   <elementGuidId>2ef8ad82-0054-4a9a-acfd-cba4819a68cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0925b3e-0116-42ae-a04c-4cde5583e81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-params</name>
      <type>Main</type>
      <value>{&quot;toasterType&quot;:&quot;AIS_INGRESS&quot;}</value>
      <webElementGuid>569dff38-2d6c-498c-b02b-8fd655ef7b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type</name>
      <type>Main</type>
      <value>DISMISS</value>
      <webElementGuid>4e2be14e-57e1-48bf-9a7f-9c88944c5768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>19bf9f51-76a2-4646-b3eb-e7b39c249c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d5236020-8139-414d-a8a1-9afc3551610c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-main&quot;)/div[@class=&quot;nav-left&quot;]/div[@class=&quot;a-section glow-toaster glow-toaster-theme-default glow-toaster-slot-default nav-coreFlyout nav-flyout&quot;]/div[@class=&quot;glow-toaster-content&quot;]/div[@class=&quot;glow-toaster-footer&quot;]/span[@class=&quot;a-button a-spacing-top-base a-button-base glow-toaster-button glow-toaster-button-dismiss a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>c42a725d-1b45-4608-9b54-5a1ef7bb72a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[2]</value>
      <webElementGuid>74811d44-1034-4858-853a-a4f97564bd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/div/div/div[3]/span/span/input</value>
      <webElementGuid>8504a3ee-8428-4dd7-ae17-48b343295e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>6de60949-a943-4fb4-82b2-8e68de0b3216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>71b6c209-362b-4d09-a0cd-304daee431b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
