<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__fluid-fat-image-link-v2_style_fluidFat_38a470</name>
   <tag></tag>
   <elementGuidId>345bd06f-593f-4a63-9872-0738b1580eb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._fluid-fat-image-link-v2_style_fluidFatImageLinkBody__1LsOX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceKsJY5iS-MGSpZqdLSq_xGw']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57c121f9-17f4-4362-95dd-3a81ba24173e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-fat-image-link-v2_style_fluidFatImageLinkBody__1LsOX</value>
      <webElementGuid>b99937cc-d99f-4b7e-a83d-49badf27d83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceKsJY5iS-MGSpZqdLSq_xGw&quot;)/a[@class=&quot;a-link-normal _fluid-fat-image-link-v2_style_mergedLinks__10JqZ&quot;]/div[@class=&quot;_fluid-fat-image-link-v2_style_fluidFatImageLinkBody__1LsOX&quot;]</value>
      <webElementGuid>5debc0c0-7480-41df-a859-7707e267fe65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceKsJY5iS-MGSpZqdLSq_xGw']/a/div</value>
      <webElementGuid>ecabc232-aaa5-47ce-8dc2-22d65a010b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/a/div</value>
      <webElementGuid>221cce96-d0a7-49d9-a345-fa3acda81d9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
