<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You are on amazon.com. You can also sho_31e5b0</name>
   <tag></tag>
   <elementGuidId>d8687d41-cc26-4149-94fb-246993070878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardInstance56HxGwLcHBRinXyycgRvvQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstance56HxGwLcHBRinXyycgRvvQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec27b7c7-1f8f-493c-95e9-bdd7ef49a445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-section a-spacing-none a-padding-base a-text-center _text-link-stripe-v2_style_textlinkstripe__3aQhz</value>
      <webElementGuid>bfb4b54b-70f1-4328-9f5e-9e2df008ea33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardInstance56HxGwLcHBRinXyycgRvvQ</value>
      <webElementGuid>b09fcc71-a150-4453-ab92-1628f1b1027b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-card-metrics-id</name>
      <type>Main</type>
      <value>text-link-stripe-v2_desktop-gateway-atf_0</value>
      <webElementGuid>4611f8c0-ada7-43dd-a143-803a23ba3c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are on amazon.com. You can also shop on Amazon India for millions of products with fast local delivery. Click here to go to amazon.in</value>
      <webElementGuid>504d6842-2e00-4948-bac5-19dc28e0e6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstance56HxGwLcHBRinXyycgRvvQ&quot;)</value>
      <webElementGuid>5f6a071e-8c00-4191-9294-c043760e24f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='CardInstance56HxGwLcHBRinXyycgRvvQ']</value>
      <webElementGuid>f67ed9b0-261c-418e-bf5f-e9e7cf077861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktop-banner-stripe']/div</value>
      <webElementGuid>7ed63da6-06c1-4e57-beea-8595cf02378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div</value>
      <webElementGuid>6747c96d-9949-470d-a48d-faf2b943a581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'CardInstance56HxGwLcHBRinXyycgRvvQ' and (text() = 'You are on amazon.com. You can also shop on Amazon India for millions of products with fast local delivery. Click here to go to amazon.in' or . = 'You are on amazon.com. You can also shop on Amazon India for millions of products with fast local delivery. Click here to go to amazon.in')]</value>
      <webElementGuid>60a86272-de55-49cb-a2f4-c33dd62e51b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
