<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New year, new suppliesShop office produ_211710</name>
   <tag></tag>
   <elementGuidId>a28bbc3a-900e-49a8-ad31-9a1a11df1571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardInstanceDFDAekv6vEsj9YyMDQQ9gw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceDFDAekv6vEsj9YyMDQQ9gw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31c9f7b0-9da7-4db7-9adb-36bde2bf996d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-cardui _fluid-fat-image-link-v2_style_fluidFatImageLink__1nw4J</value>
      <webElementGuid>0a771bdf-1a87-4819-aa38-dae4dc5e9dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-card-type</name>
      <type>Main</type>
      <value>basic</value>
      <webElementGuid>18ef0847-ab46-4d4a-916b-5574fac27e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardInstanceDFDAekv6vEsj9YyMDQQ9gw</value>
      <webElementGuid>2f9faf33-3de1-4f72-a5b3-b7ee2e5943a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-card-metrics-id</name>
      <type>Main</type>
      <value>fluid-fat-image-link-v2_desktop-gateway-atf_4</value>
      <webElementGuid>1f052b44-92c5-414f-a678-050be9c1e273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New year, new suppliesShop office productsShop office products</value>
      <webElementGuid>07eb3c34-bbce-4e47-b0c6-7c6cee90c121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceDFDAekv6vEsj9YyMDQQ9gw&quot;)</value>
      <webElementGuid>b853c9dc-ea8c-434b-b584-a9abc136e2ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceDFDAekv6vEsj9YyMDQQ9gw']</value>
      <webElementGuid>1c9a08ef-6fd7-4ad5-9ca2-72e025fddd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktop-grid-4']/div</value>
      <webElementGuid>ba69d942-f3df-4a87-983b-e1663a21fc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>0d84de0f-0b38-4041-acae-fcc0a72d6b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'CardInstanceDFDAekv6vEsj9YyMDQQ9gw' and (text() = 'New year, new suppliesShop office productsShop office products' or . = 'New year, new suppliesShop office productsShop office products')]</value>
      <webElementGuid>f1652348-f2ec-4bfd-9118-90820bccb5e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
