<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>75d41967-d8a5-4f79-b3a3-ea30668f9083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;COMFIER neck, back massagers and more&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceuRn3ettcrRKjxQhR2JUEww']/div[2]/div/a/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>934a1788-f970-4b0d-a61e-96cb67c221c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>COMFIER neck, back massagers and more</value>
      <webElementGuid>acd6280a-d197-4b99-9565-f7ce9a8ead80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/418x2hS-77L._AC_SY230_.jpg</value>
      <webElementGuid>4fe41144-9440-458c-a7f9-eb78cc608e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/418x2hS-77L._AC_SY460_.jpg</value>
      <webElementGuid>ba3ed4fe-d29b-4e39-bfb8-2eb124f85a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceuRn3ettcrRKjxQhR2JUEww&quot;)/div[@class=&quot;a-cardui-body&quot;]/div[1]/a[@class=&quot;a-spacing-small a-link-normal a-text-normal&quot;]/div[@class=&quot;a-section a-spacing-small&quot;]/div[@class=&quot;a-section a-spacing-mini center-image aok-block&quot;]/div[@class=&quot;a-image-container a-dynamic-image-container&quot;]/img[1]</value>
      <webElementGuid>93443f2d-d7cd-4f9e-a853-5a722eefe1e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceuRn3ettcrRKjxQhR2JUEww']/div[2]/div/a/div/div/div/img</value>
      <webElementGuid>19437b59-e20b-4bc8-92e4-a2751141c5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='COMFIER neck, back massagers and more']</value>
      <webElementGuid>cd79aa99-9255-4bb7-b9bb-5c10b10af685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>b83263d9-373b-49a9-a2b1-5610661b2872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'COMFIER neck, back massagers and more' and @src = 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/418x2hS-77L._AC_SY230_.jpg']</value>
      <webElementGuid>e722c708-c99c-4559-bfdc-e486e362136d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
