<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__fluid-fat-image-link-v2_style_fluidLan_075a06</name>
   <tag></tag>
   <elementGuidId>efa30444-0626-4dfe-959c-62136fd57728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img._fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK._fluid-fat-image-link-v2_style_fluidImage__gTBjA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceKsJY5iS-MGSpZqdLSq_xGw']/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b7da470c-2fb2-46a5-906a-80e559530a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Deals in PCs</value>
      <webElementGuid>54df5100-06c7-4c0c-b526-42c1ad41b57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/W/MEDIAX_849526-T1/images/G/01/AmazonExports/Events/2023/EBF23/Fuji_Desktop_Single_image_EBF_1x_v1._SY304_CB573698005_.jpg</value>
      <webElementGuid>dfe61e77-cece-4c7e-97ae-1c3b7cdbb881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK _fluid-fat-image-link-v2_style_fluidImage__gTBjA</value>
      <webElementGuid>579189ff-4ef0-4552-9845-ccaf30c60192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/W/MEDIAX_849526-T1/images/G/01/AmazonExports/Events/2023/EBF23/Fuji_Desktop_Single_image_EBF_2x_v1._SY608_CB573698005_.jpg</value>
      <webElementGuid>f8ed2d8d-0767-4c89-8158-04777426f923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceKsJY5iS-MGSpZqdLSq_xGw&quot;)/a[@class=&quot;a-link-normal _fluid-fat-image-link-v2_style_mergedLinks__10JqZ&quot;]/div[@class=&quot;_fluid-fat-image-link-v2_style_fluidFatImageLinkBody__1LsOX&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-fat-image-link-v2_style_fluidImageContainer__2SOMr&quot;]/img[@class=&quot;_fluid-fat-image-link-v2_style_fluidLandscapeImage__2euAK _fluid-fat-image-link-v2_style_fluidImage__gTBjA&quot;]</value>
      <webElementGuid>dafb407e-c748-4298-92d2-943d01d787ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceKsJY5iS-MGSpZqdLSq_xGw']/a/div/div/img</value>
      <webElementGuid>722f4051-b3a0-4d87-b47b-2ffd3c6e91b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Deals in PCs']</value>
      <webElementGuid>d7e81a2a-93aa-4354-87be-9bd5701a0cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/img</value>
      <webElementGuid>3d1095f6-cc27-4b3a-9f68-1a6d1d9dff91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Deals in PCs' and @src = 'https://images-na.ssl-images-amazon.com/images/W/MEDIAX_849526-T1/images/G/01/AmazonExports/Events/2023/EBF23/Fuji_Desktop_Single_image_EBF_1x_v1._SY304_CB573698005_.jpg']</value>
      <webElementGuid>f351892e-883d-4ecf-a272-f9c7192c80c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
