<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imglandingImage</name>
   <tag></tag>
   <elementGuidId>39b3c7c4-7e7a-4ddd-b81c-3e1075ed3238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#landingImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='landingImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0edddb9-2c98-417f-821f-3ceafce09c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>5 Pack Men’s Active Quick Dry Crew Neck T Shirts | Athletic Running Gym Workout Short Sleeve Tee Tops Bulk</value>
      <webElementGuid>7714b5e2-e058-48f7-bfae-1cf13e41c1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX425_.jpg</value>
      <webElementGuid>fe8aa5c8-551a-4f81-bcc1-72011048104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-old-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SL1500_.jpg</value>
      <webElementGuid>73b5359e-0cb0-47a3-8208-4a2502f08834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>markFeatureRenderForImageBlock(); if(this.width/this.height > 0.77){this.className += ' a-stretch-horizontal'}else{this.className += ' a-stretch-vertical'};this.onload='';setCSMReq('af');if(typeof addlongPoleTag === 'function'){ addlongPoleTag('af','desktop-image-atf-marker');};setCSMReq('cf')</value>
      <webElementGuid>22ab07a9-6a47-4afc-8cd2-694d630ae235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-image-name</name>
      <type>Main</type>
      <value>landingImage</value>
      <webElementGuid>1a5a6bc6-1164-48ae-9a74-8025e4f9769e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dynamic-image a-stretch-horizontal</value>
      <webElementGuid>210e3a4b-50d5-4cde-b162-3ff5aa17b670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landingImage</value>
      <webElementGuid>a961e79f-37b2-498d-b701-0fbf28f8f7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-dynamic-image</name>
      <type>Main</type>
      <value>{&quot;https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX342_.jpg&quot;:[443,342],&quot;https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX679_.jpg&quot;:[879,679],&quot;https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX466_.jpg&quot;:[603,466],&quot;https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX425_.jpg&quot;:[550,425],&quot;https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX522_.jpg&quot;:[675,522],&quot;https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX569_.jpg&quot;:[736,569],&quot;https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX385_.jpg&quot;:[498,385]}</value>
      <webElementGuid>93caef37-6a49-4340-b73a-e55570b6ebfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingImage&quot;)</value>
      <webElementGuid>94f0ceed-59bc-4bfc-a1c6-b32be352d225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='landingImage']</value>
      <webElementGuid>9f2a802e-05e5-48da-a36f-d6a08b126e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imgTagWrapperId']/img</value>
      <webElementGuid>f406dfca-e79c-4684-9823-3fffbbdff815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='5 Pack Men’s Active Quick Dry Crew Neck T Shirts | Athletic Running Gym Workout Short Sleeve Tee Tops Bulk']</value>
      <webElementGuid>b2471a76-50f5-44ae-8fe1-d11987d28e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/img</value>
      <webElementGuid>56a39e3c-22bb-4a59-aa25-00f04e940f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '5 Pack Men’s Active Quick Dry Crew Neck T Shirts | Athletic Running Gym Workout Short Sleeve Tee Tops Bulk' and @src = 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/81oWf0Q47KL._AC_SX425_.jpg' and @id = 'landingImage']</value>
      <webElementGuid>8765b21d-1b69-4f71-8548-598e8d273301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
