<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Size</name>
   <tag></tag>
   <elementGuidId>3a4ac82e-83da-4f6d-b244-edcd7b05f594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-row.a-spacing-micro > label.a-form-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='variation_size_name']/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>138397e8-e895-4fa8-b48b-731f99faf586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-form-label</value>
      <webElementGuid>4b936794-a036-4636-a3f8-4730a7bec91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Size:</value>
      <webElementGuid>21602b35-64a8-48a3-92fd-15694e47da03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;variation_size_name&quot;)/div[@class=&quot;a-row a-spacing-micro&quot;]/label[@class=&quot;a-form-label&quot;]</value>
      <webElementGuid>31ee2199-22c4-4b97-9422-330503972bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='variation_size_name']/div[2]/label</value>
      <webElementGuid>55768898-e34e-403c-84fe-8e0e5b1cb8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>5754268f-8789-475b-8681-325f01688bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Size:' or . = 'Size:')]</value>
      <webElementGuid>a99b179c-be14-4c2e-b820-0e52becce03d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
